### ISSUE TITLE
API Problem

### ISSUE THREAD

**Issue by George-Catalin** [codeastar/easy_cheap_flights_checker#1]
When I am using  $Env:SKYSCAN_RAPID_API_KEY="you_api_key" in anaconda i get this error : The filename, directory name, or volume label syntax is incorrect. 
What should I do?

**Comment by codeastar** [comment]
The $Env syntax is used under Windows' Powershell to set environment variable.
For Anaconda, you can try using "conda env config vars set SKYSCAN_RAPID_API_KEY=YOUR_API_KEY" .

**Comment by George-Catalin** [comment]
When I run it as below, I get the following error now 

conda env export (config is not recognized) vars set SKYSCAN_RAPID_API_KEY="5a38b44000msh7b4655ad6dc5756p1b8f84jsne27843776e69"
usage: conda-env-script.py [-h] {create,export,list,remove,update} ...
conda-env-script.py: error: unrecognized arguments: vars set SKYSCAN_RAPID_API_KEY="my API"

**Comment by George-Catalin** [comment]
When I run it as below, I get the following error now

conda env export (config is not recognized) vars set SKYSCAN_RAPID_API_KEY="my API"
usage: conda-env-script.py [-h] {create,export,list,remove,update} ...
conda-env-script.py: error: unrecognized arguments: vars set SKYSCAN_RAPID_API_KEY="my API"

**Comment by codeastar** [comment]
How about using the good old SET command? 

>set SKYSCAN_RAPID_API_KEY=YOUR_KEY

**Comment by George-Catalin** [comment]
It worked! However when i run the program from anaconda... I get no output, basically nothing happens. What am I doing wrong? Sorry for asking so many silly questions!!!

**Comment by George-Catalin** [comment]
I have solved everything !!! Thank you for the help and for your time!
